#!/bin/sh

userresources=$XDG_CONFIG_HOME/x11/xresources
usermodmap=$XDG_CONFIG_HOME/x11/xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi


# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# keymap 
setxkbmap -option caps:escape

# startup apps
udiskie &
picom &
dunst &
blueberry-tray &
sxhkd &
~/.scripts/alias/mpd
/bin/bash -c "sleep 30 && python3 /home/mokou/.scripts/calcurse_reminders" &
~/.scripts/system/wallpaper

exec i3
