***REMOVED***!/bin/sh

userresources=$XDG_CONFIG_HOME/x11/xresources
usermodmap=$XDG_CONFIG_HOME/x11/xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

***REMOVED*** merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

***REMOVED*** start some nice program

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f-
fi

***REMOVED*** keymap 
setxkbmap -option caps:escape
syndaemon -i 0.3 -t -K -R & ***REMOVED*** disable trackpad for 0.3 seconds after touching the keyboard

***REMOVED*** startup apps
udiskie &
picom --experimental-backends -b &
dunst &
blueberry-tray &
sxhkd &
calcurse --daemon
~/.scripts/alias/mpd &
***REMOVED***~/.scripts/screenlayout/rog_zephyrus_dual.sh &
~/.scripts/system/wallpaper &
~/.scripts/alias/searx &
safeeyes &
exec i3
