#!/bin/sh

userresources=${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources
usermodmap=${XDG_CONFIG_HOME:-$HOME/.config}/x11/xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice program

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f-
fi

# keymap
syndaemon -i 0.3 -t -K -R & # disable trackpad for 0.3 seconds after touching the keyboard

# startup apps
udiskie &
picom --experimental-backends -b &
dunst &
blueberry-tray &
sxhkd &
calcurse --daemon
~/.scripts/alias/mpd &
~/.scripts/system/wallpaper &
~/.scripts/alias/searx &
~/.local/bin/remaps &
#~/.local/bin/xmonitors &
light -S 70 &
exec i3
