#!/bin/sh

# This is a basic command that searches for scripts in the script directory
# It opens them with $EDITOR. It only includes files (not directories)
# It is piped into fzf where it is selected.
function se {
    CHOICE=$(fd . $XDG_SOURCE_HOME/examples/bash -t f | sed "s|$HOME/||g" | fzf) 
    [ -n "$CHOICE" ] && $EDITOR $HOME/$CHOICE
}

# Instead executes script
function sx {
    CHOICE=$(fd . $XDG_SOURCE_HOME/examples/bash -t f | sed "s|$HOME/||g" | fzf) 
    [ -n "$CHOICE" ] && $HOME/$CHOICE
}

# searches history
function hf {
    print -z $( ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s --tac --height "50%" | sed -E 's/ *[0-9]*\*? *//' | sed -E 's/\\/\\\\/g')
}

# fzfcd
function fcd {
    cd $(ls | fzf)
}

# serach man pages
# function fzman {
#     OLDIFS="$IFS"
#     IFS=":"
#     MANPATHS=($(manpath))
#     IFS=$OLDIFS

#     MANS=()
#     for MAN in $MANPATHS
#     do
#         MANTOADD=$(/bin/ls $MAN/man*)
#         MANS+=${MANTOADD%%.*}
#     done

#     man $(echo ${MANS} | fzf)
# }
