#!/bin/sh
# This script runs at startup, to be started by the Window Manager

~/.scripts/alias/mpd


KANBAN_FILE="$HOME/documents/kanban/$(date '+%g-%m-%d')_taskell.md"
[ -z $KANBAN_FILE ] && cat ~/.config/taskell/template.md > $KANBAN_FILE
kitty calcurse &!
kitty taskell $KANBAN_FILE &!
kitty lvim ~/vimwiki/better_learning/how_to_learn.rmd &!

notify-send "Good luck! Remember you have to be great"
