#!/bin/sh

DOWNLOADER="yt-dlp-old"
COOKIES="~/.local/share/yt-dlp/cookies.txt"

function yt_notif {
    dunstify -u low -i 'youtube-dl' -a 'youtube-dl-notification' $1 $2
}

# [ -z "$COOKIES" ] && echo "You need to set your cookies path in '$XDG_CONFIG_HOME/script/ytdl_scripts"
# [ -z "$(whence $DOWNLOADER)" ] && echo "You need to set your youtube-dl command in '$XDG_CONFIG_HOME/script/ytdl_scripts'"
